export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS"
export const FETCH_TEMPLATES_LOADING = "FETCH_TEMPLATES_LOADING"
export const FETCH_TEMPLATES_FAILED = "FETCH_TEMPLATES_FAILED"
export const FILTER_TEMPLATES = "FILTER_TEMPLATES"


export const NEXT_PAGE = "NEXT_PAGE"
export const PREVIOUS_PAGE = "PREVIOUS_PAGE"
export const PAGE_TARGET = "PAGE_TARGET"