export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS"
export const FETCH_TEMPLATES_LOADING = "FETCH_TEMPLATES_LOADING"
export const FETCH_TEMPLATES_FAILED = "FETCH_TEMPLATES_FAILED"
export const FILTER_TEMPLATES = "ADD_POST"
